name: Deploy NestJS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma Client
        run: |
          # File dhoondne ka pakka tareeqa
          SCHEMA_FILE=$(find . -name "schema.prisma" -not -path "*/node_modules/*" | head -n 1)
          echo "Schema found at: $SCHEMA_FILE"
          
          # Prisma generate command
          npx prisma generate --schema=$SCHEMA_FILE
        env:
          DATABASE_URL: "postgresql://drivesafewarranty:lkajd65736%5Ejdb000%2D0JJh@127.0.0.1:5432/drivesafewarranty_db"

      - name: Build Project
        run: npm run build

      - name: SFTP Deploy (Dist and Package)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './dist' 
          remote_path: '/var/www/drivesafe-backend-updated/dist'
          delete_remote_files: true

      - name: SFTP Deploy (Root Files)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './package*.json'
          remote_path: '/var/www/drivesafe-backend-updated'
